name: ci

on:
  push:
  pull_request:

jobs:
  validate-template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Validate plugin template
      run: ./mill g8.validate